version: '3.5'

services:
  raft:
    image: raft
    network_mode: host
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    depends_on:
      - gluster

  gluster:
    image: gluster
    privileged: true
    environment:
      - NET_IFACE=eth0
    network_mode: host
    volumes:
      - gluster:/data:rw

volumes:
  gluster:
