services:
  orchestration:
    image: orchestration
    network_mode: host
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - test:/test
    privileged: true
    depends_on:
          - gluster
  gluster:
    image: gluster
    privileged: true
    env_file:
      - .env
    network_mode: host
    volumes:
      - gluster:/data:rw

volumes:
  gluster:
  test:
