version: "3.8"

services:
  gluster:
    image: gluster
    hostname: gluster-__IDX__
    privileged: true
    env_file:
      - .env
    volumes:
      - ./data/gluster-__IDX__:/data
    networks:
      - gluster_net

  orchestration:
    image: orchestration
    env_file:
      - .env
    environment:
      SERVER: gluster-__IDX__
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/test-__IDX__:/test
    privileged: true
    depends_on:
      - gluster
    networks:
      - orchestration_net
      - gluster_net

networks:
  gluster_net:
    external: true
    name: gluster_net
  orchestration_net:
    external: true
    name: orchestration_net
